config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    get :followings, on: :member
    get :followers, on: :member
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: "User"
  
  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:relationship][:follow_id])
    following = current_user.follow(@user)
    if following.save
      flash[:success] = "ユーザーをフォローしました"
      redirect_to @user
    else
      flash.now[:alert] = "ユーザーのフォローに失敗しました"
      redirect_to @user
    end
  end

  def destroy
    @user = User.find(params[:follow_id])
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = "ユーザーのフォローを解除しました"
      redirect_to @user
    else
      flash.now[:alert] = "ユーザーのフォロー解除に失敗しました"
      redirect_to @user
    end
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_form.html.erb
  <% unless current_user == user %>
    <!--フォロー解除ボタン-->
    <% if current_user.following?(user) %>
    <%= form_with model: @relationship, url: relationship_path(@user), method: :delete, local: true do |f| %>
      <%= f.hidden_field :follow_id, value: user.id %>
      <%= f.submit "フォローを解除する" %>
    <% end %>
    <!----フォローボタン-->
  <% else %>
    <%= form_with model: @set_relationship, url: relationships_path, local: true do |f| %>
      <%= f.hidden_field :follow_id, value: user.id %>
      <%= f.submit "フォロー" %>
      <% end %>
    <% end %>
  <% end %>